import type { NextPage } from "next";
import Layout from "../components/Layout";
import Head from "next/head";
import Card from "../components/Card";

const Home: NextPage = () => {
  return (
    <Layout isHome>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Card />
      <Card />
      <Card />
    </Layout>
  );
};

export default Home;
